[app]
title = J.A.R.V.I.S
package.name = jarvis
package.domain = org.digitalpixel
version = 1.0
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
requirements = python3,kivy,pyjnius
orientation = portrait
fullscreen = 1
android.permissions = INTERNET,RECORD_AUDIO,READ_CONTACTS,CALL_PHONE,READ_SMS,SEND_SMS,READ_PHONE_STATE
android.api = 35
android.api_min = 26
android.ndk = 27b
android.build_tools_version = 35.0.0
android.accept_sdk_license = True
android.archs = arm64-v8a
android.format = apk
android.release_artifact = apk
android.logcat_filters = *:S JARVIS:V Python:V AndroidRuntime:E
